// PrismaClient comes from the runtime package (types generated by `prisma generate`).
// During local dev/CI, run `yarn db:generate` first to get full type safety.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export { PrismaClient } from '@prisma/client';

// Model type stubs — replaced by generated types after `yarn db:generate`.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type User = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Profile = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Project = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Connection = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Match = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Investment = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Message = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Prisma = any;

// ─── Enums (mirrored from schema.prisma so they compile without generated client) ───
export * from './enums';

export { getClient, getClientForRegion, disconnectAll } from './client';
export { getGlobalClient, disconnectGlobal } from './globalClient';
